### ISSUE TITLE
Epic Planning for BackEnd

### ISSUE THREAD

**Issue by stacysealky** [donategifts/ts-backend#6]
## Epic 2- rewrite v1 to v2 (BackEnd) 

Rewrite existing v1 features and pages for BE.

Stories and following tasks:

### Story 1. Migration to SQL

- [ ] Create schemas - Patric has a diagram

### Story 2. Controllers and connectors

- [ ] #64
- [ ] #65
- [ ] Wishcards creation & logic  
- [ ] need postman set up 
- [x] Account Creation, Firebase implementation, address creation (good enough)

### Story 3. Prepare API gateway / endpoints for data

- [ ] Use OpenAPI to generate endpoints

## Epic 3 - email full automation 

1. when user donates and payment successful, notify the agency
2. when amazon order is placed and order is confirmed, send email to donor
3. when amazon order is placed and order is confirmed, send email to agency ( future: with message button -> page to send message to donor. ) 
4. make an email subscription setting - boolean flag check for each email

## Epic 4 - Zinc API + order full automation 

- [ ] store api keys and secret keys in the droplet? - look into this
- [ ] order immediately after stripe/paypal payment completed ?
- [ ] credit card/ amazon vendor account prepay the account? (look into this) 
- [ ] possibly add the search feature so the user can search for amazon items within our site (1cent per queries) -> limit? 10 seconds and upper limit of 100/day? maybe
- [ ] monitor endpoint and raise suspicious activity alert 
- [ ] articleNumber, maxPrice 
- [ ] separate amazon account? donate gifts credit card? need vendor account or organization account? 
- [ ] order from walmart and other marketplace sites? - maybe later?
